name: 'test'

on:
  push:
    branches:
      - "main"
      - "dev"
      - "test"
  pull_request:
    branches:
      - '*'

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        python-version: ['3.10', '3.11', '3.12', '3.13', '3.14']
    runs-on: ${{ matrix.os }}
    env:
      PIP_NO_INPUT: "1"
      PYTHON_KEYRING_BACKEND: "keyring.backends.null.Keyring"
      PIP_DEFAULT_TIMEOUT: "60"
      PIP_RETRIES: "5"
    steps:
      - uses: actions/checkout@v4
      - name: Install OpenMP
        if: runner.os == 'macOS'
        run: brew install libomp
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install uv
        uses: astral-sh/setup-uv@v3
      - name: Install hatch
        run: uv pip install --system hatch "virtualenv<21"
      - name: Install swig
        run: uv pip install --system swig
      - name: Run tests
        run: hatch -vv run pytest -vv
        timeout-minutes: 20
